language: node_js
node_js:
  - "4.2"
sudo: false

before_script:
  - npm install -g gulp bower node-inspector bower karma karma-cli

script:
  - gulp test

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true

