language: node_js
node_js:
  - "4.2"
sudo: false

before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma
  - npm install -g karma-cli
  - bower install

script:
  - gulp views
  - gulp scripts
  - gulp test

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true

